#!/usr/bin/env bash

set -euxo pipefail

INITIAL_MEMORY_PAGES=2000
MAX_MEMORY_PAGES=65536
PAGE_SIZE=65536

echo "// Generated by build.sh - do not edit
var WASM_INITIAL_MEMORY_PAGES = $INITIAL_MEMORY_PAGES;
var WASM_MAX_MEMORY_PAGES = $MAX_MEMORY_PAGES;" > web/wasm-config.js

INITIAL_MEMORY_BYTES=$(expr $INITIAL_MEMORY_PAGES \* $PAGE_SIZE)
MAX_MEMORY_BYTES=$(expr $MAX_MEMORY_PAGES \* $PAGE_SIZE)

ODIN_ROOT=$(odin root)
ODIN_JS="$ODIN_ROOT/core/sys/wasm/js/odin.js"
WGPU_JS="$ODIN_ROOT/vendor/wgpu/wgpu.js"

odin build . -target:js_wasm32 -out:web/microui.wasm -o:size -define:MICROUI_MAX_WIDTHS=24 \
	-extra-linker-flags:"--export-table --import-memory --initial-memory=$INITIAL_MEMORY_BYTES --max-memory=$MAX_MEMORY_BYTES"

cp $ODIN_JS web/odin.js
cp $WGPU_JS web/wgpu.js
